/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paintsystem;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ADMIN
 */
public class INVENTORY extends javax.swing.JFrame {

     Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs;
    public INVENTORY() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventtable = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        product_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventtable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inventtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PRODUCT ID", "TYPE", "BRAND NAME", "PRODUCT NAME", "PRICE", "STOCKS"
            }
        ));
        inventtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inventtable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 580, 420));

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 280, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("SEARCH:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 60, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-go-back-16.png"))); // NOI18N
        jButton4.setText("BACK");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 30));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setText("ADD STOCKS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("STOCKS:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("PRICE:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("PRODUCT NAME:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));
        jPanel2.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 130, 30));

        Price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PriceKeyTyped(evt);
            }
        });
        jPanel2.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, 30));

        Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityActionPerformed(evt);
            }
        });
        Quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantityKeyTyped(evt);
            }
        });
        jPanel2.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 130, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-update-24.png"))); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 110, 30));
        jPanel2.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("BRAND NAME:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("TYPE:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 20));

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT TYPE", "Enamel Paint", "Emulsion Paint", "Oil paint", "Anti-Corrosive Paint", "Synthetic Rubber Paint", "Latex paint", "Acrylic Paint", "Silicon Paint", "Alkyd Paint" }));
        jPanel2.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-add-16.png"))); // NOI18N
        jButton2.setText("ADD STOCKS");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 110, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-remove-24.png"))); // NOI18N
        jButton3.setText("DELETE STOCKS");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 130, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/74b7b3858ededae65860deffcd527b8b-removebg-preview.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -50, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 340, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/a56e20150b4ee9e901847dd5723280b5-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, 500));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/a56e20150b4ee9e901847dd5723280b5-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        product_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   ADMINMENU s= new ADMINMENU();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      conn = DBConnection.getConnection();
      retrieve();
    }//GEN-LAST:event_formWindowOpened

    private void inventtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventtableMouseClicked
      DefaultTableModel model=(DefaultTableModel)inventtable.getModel();
int selectedRowIndex=inventtable.getSelectedRow();
   product_id.setText(model.getValueAt(selectedRowIndex, 0).toString());
type.setSelectedItem(model.getValueAt(selectedRowIndex, 1).toString());
brand.setText(model.getValueAt(selectedRowIndex, 2).toString());
pname.setText(model.getValueAt(selectedRowIndex, 3).toString());
Price.setText(model.getValueAt(selectedRowIndex, 4).toString());
Quantity.setText(model.getValueAt(selectedRowIndex, 5).toString());  
    }//GEN-LAST:event_inventtableMouseClicked

    private void PriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PriceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceKeyReleased

    private void PriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PriceKeyTyped
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))){
            evt.consume();
        }
    }//GEN-LAST:event_PriceKeyTyped

    private void QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityActionPerformed

    private void QuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityKeyTyped
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))){
            evt.consume();
        }
    }//GEN-LAST:event_QuantityKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        update();
       retrieve();
        product_id.setText("");
        type.setSelectedItem("SELECT TYPE");
        brand.setText("");
        pname.setText("");
        Price.setText("");
        Quantity.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        save_data();
      retrieve();
       product_id.setText("");
        type.setSelectedItem("SELECT TYPE");
        brand.setText("");
        pname.setText("");
        Price.setText("");
        Quantity.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   delete();
   retrieve();
    product_id.setText("");
        type.setSelectedItem("SELECT TYPE");
        brand.setText("");
        pname.setText("");
        Price.setText("");
        Quantity.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        try {
    String a = "%"+search.getText()+"%";
   
    String sql = "SELECT Product_id AS 'PRODUCT ID',Type AS 'TYPE',brandname AS 'BRAND NAME', productname AS 'PRODUCT NAME',price AS 'PRICE',Stocks AS 'STOCKS'  FROM inventory WHERE Product_id LIKE'" + a+"' OR Type LIKE'" + a+"' OR  Brandname LIKE'" + a+"' OR 	Productname LIKE'" + a+"' OR Price LIKE'" + a+"' OR Stocks LIKE'" + a+"'";
pst = conn.prepareStatement(sql);
rs = pst.executeQuery();
inventtable.setModel(DbUtils.resultSetToTableModel(rs));
} catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INVENTORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INVENTORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INVENTORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INVENTORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INVENTORY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField brand;
    private javax.swing.JTable inventtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pname;
    private javax.swing.JLabel product_id;
    private javax.swing.JTextField search;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables

private void retrieve(){
try {
    String sql = "SELECT Product_id AS 'PRODUCT ID',Type AS 'TYPE',brandname AS 'BRAND NAME', productname AS 'PRODUCT NAME',price AS 'PRICE',Stocks AS 'STOCKS'  FROM inventory";
pst = conn.prepareStatement(sql);
rs =pst.executeQuery();
inventtable.setModel(DbUtils.resultSetToTableModel(rs));
inventtable.removeColumn(inventtable.getColumnModel().getColumn(0));
}catch(Exception e){
   JOptionPane.showMessageDialog(rootPane, e);
}
}private void save_data(){
    String one = (String)type.getSelectedItem();

    String three = brand.getText();
    String four = pname.getText();
    String five = Price.getText();
    String six = Quantity.getText();
    
   if (one.equals("")||three.equals("")||four.equals("")||five.equals("")||six.equals("")){
       JOptionPane.showMessageDialog(null, "SOME FIELDS ARE EMPTY");
   }else{
       try{
        
  String sql= "INSERT INTO inventory(Type,Brandname,Productname,Price,Stocks)VALUE(?,?,?,?,?)";
   pst = conn.prepareStatement(sql);
 
   pst.setString(1, (String) type.getSelectedItem());
   pst.setString(2,brand.getText());  
   pst.setString(3,pname.getText());
   pst.setString(4,Price.getText());
   pst.setString(5,Quantity.getText());
       pst.execute();
      JOptionPane.showMessageDialog(null,"Stocks Added");
    }catch(Exception e){
      JOptionPane.showMessageDialog(null,e);
    }
}
   }
   private void update(){
        String one = (String)type.getSelectedItem();
    String three = brand.getText();
    String four = pname.getText();
    String five = Price.getText();
    String six = Quantity.getText();
    
   if (one.equals("")||three.equals("")||four.equals("")||five.equals("")||six.equals("")){
       JOptionPane.showMessageDialog(null, "SOME FIELDS ARE EMPTY");
   }else{
    try{
        String sql="UPDATE inventory SET Product_id = ?,Type=?, Brandname=?,Productname=?,Price=?,Stocks=? WHERE Product_id = '"+product_id.getText()+"'";
   pst = conn.prepareStatement(sql);
   pst.setString(1,product_id.getText());  

   pst.setString(2, (String) type.getSelectedItem());
   pst.setString(3,brand.getText());  
   pst.setString(4,pname.getText());
   pst.setString(5,Price.getText());
   pst.setString(6,Quantity.getText());
       pst.execute();
        JOptionPane.showMessageDialog(null, "Stocks Updated Successfully");
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
}
   }
private void delete(){
    try{
        String sql = "SELECT * FROM inventory WHERE Product_id='"+product_id.getText()+"'";
         pst = conn.prepareStatement(sql);
         rs=pst.executeQuery();
         if (rs.next()){
             String sql1 = "DELETE FROM inventory WHERE Product_id='"+product_id.getText()+"'";
               pst = conn.prepareStatement(sql1);
             pst.execute();
             JOptionPane.showMessageDialog(null, "Stocks Deleted Permanently");
         }else{
             JOptionPane.showMessageDialog(null, "No Existing Data");
         }
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
}
}}

