/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paintsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ADMIN
 */
public class MANAGEUSER extends javax.swing.JFrame {
       Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs;

    public MANAGEUSER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jpass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Acctype = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manage = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        acc_id = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTER ACCOUNT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 430, 50));
        jPanel1.add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 230, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Account Type:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, 30));
        jPanel1.add(jpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 230, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, 30));
        jPanel1.add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 230, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-eye-24.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 110, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-update-24.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 140, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-go-back-16.png"))); // NOI18N
        jButton2.setText("BACK");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 30));

        Acctype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Acctype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ACCOUNT TYPE", "Admin", "Cashier" }));
        jPanel1.add(Acctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 230, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Full Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 110, 30));

        manage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Account ID", "Account Type", "Full Name", "Username"
            }
        ));
        manage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(manage);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 540, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/89f6367919ecd20ff6318c52ce6ad130-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -10, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/usersignup.png"))); // NOI18N
        jButton3.setText("Signup");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 140, 40));

        acc_id.setText("jLabel7");
        jPanel1.add(acc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-remove-24.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 850, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String type = (String) Acctype.getSelectedItem();
     String fullname = jname.getText();
     String username = jusername.getText();
     String password = jpass.getText();
    if (fullname.equals("")||username.equals("")|| password.equals("")){
       JOptionPane.showMessageDialog(null, "SOME FIELDS ARE EMPTY");
   }else if(type.equals("SELECT ACCOUNT TYPE")){
     JOptionPane.showMessageDialog(null, "PLEASE SELECT ACCOUNT TYPE");
   }else{
   }
    update();
         retrieve();
    acc_id.setText("");
      Acctype.setSelectedItem("SELECT ACCOUNT TYPE");
      jname.setText("");
        jusername.setText("");
          jpass.setText("");
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     conn = DBConnection.getConnection();
      retrieve();
    }//GEN-LAST:event_formWindowOpened

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
            jpass.setEchoChar((char)0);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
           jpass.setEchoChar('*');
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ADMINMENU s= new   ADMINMENU();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      signup();
       retrieve();
    acc_id.setText("");
      Acctype.setSelectedItem("SELECT ACCOUNT TYPE");
      jname.setText("");
        jusername.setText("");
          jpass.setText("");
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void manageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMouseClicked
      DefaultTableModel model=(DefaultTableModel)manage.getModel();
int selectedRowIndex=manage.getSelectedRow();
   acc_id.setText(model.getValueAt(selectedRowIndex, 0).toString());
Acctype.setSelectedItem(model.getValueAt(selectedRowIndex, 1).toString());
jname.setText(model.getValueAt(selectedRowIndex, 2).toString());
jusername.setText(model.getValueAt(selectedRowIndex, 3).toString());
jpass.setText(model.getValueAt(selectedRowIndex, 4).toString());

    }//GEN-LAST:event_manageMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      delete();
        retrieve();
    acc_id.setText("");
      Acctype.setSelectedItem("SELECT ACCOUNT TYPE");
      jname.setText("");
        jusername.setText("");
          jpass.setText("");
   
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MANAGEUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MANAGEUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MANAGEUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MANAGEUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MANAGEUSER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Acctype;
    private javax.swing.JLabel acc_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jname;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JTextField jusername;
    private javax.swing.JTable manage;
    // End of variables declaration//GEN-END:variables
private void signup(){
  try{
      String type = (String) Acctype.getSelectedItem();
  
     String fullname = jname.getText();
     String username = jusername.getText();
     String password = jpass.getText();
    if (fullname.equals("")||username.equals("")|| password.equals("")){
       JOptionPane.showMessageDialog(null, "SOME FIELDS ARE EMPTY");
   }else if(type.equals("SELECT ACCOUNT TYPE")){
     JOptionPane.showMessageDialog(null, "PLEASE SELECT ACCOUNT TYPE");
   }else{

   String sql = "INSERT INTO users(Account_type, Full_name,Account_username,Account_password) VALUE (?,?,?,?)";
                pst = conn.prepareStatement(sql);  
                 

   pst.setString(1, (String) Acctype.getSelectedItem());
      pst.setString(2,jname.getText());
   pst.setString(3,jusername.getText());  
   pst.setString(4,jpass.getText());
       pst.execute();
        JOptionPane.showMessageDialog(null, "Account Created Successfully");
   }
}catch(Exception e){
}
}
    private void retrieve(){
try {
    String sql = "SELECT Account_id AS 'Account ID', Account_type AS 'Account Type',Full_name AS 'Full Name',Account_username AS 'Username', Account_password AS 'Password' FROM users";
pst = conn.prepareStatement(sql);
rs =pst.executeQuery();
manage.setModel(DbUtils.resultSetToTableModel(rs));
manage.removeColumn(manage.getColumnModel().getColumn(0));
}catch(Exception e){
   JOptionPane.showMessageDialog(rootPane, e);
}
}
   private void update(){
     String type = (String) Acctype.getSelectedItem();
     String fullname = jname.getText();
     String username = jusername.getText();
     String password = jpass.getText();
    if (fullname.equals("")||username.equals("")|| password.equals("")){
       JOptionPane.showMessageDialog(null, "SOME FIELDS ARE EMPTY");
   }else if(type.equals("SELECT ACCOUNT TYPE")){
     JOptionPane.showMessageDialog(null, "PLEASE SELECT ACCOUNT TYPE");
   }else{
    try{
        String sql="UPDATE users SET Account_id = ?,Full_name=?,Account_type=?,Account_username=?,Account_password=? WHERE Account_id= '"+acc_id.getText()+"'";
     
 
    
   pst = conn.prepareStatement(sql);
   pst.setString(1,acc_id.getText());  
   pst.setString(2,jname.getText());
   pst.setString(3, (String) Acctype.getSelectedItem());
   pst.setString(4,jusername.getText());  
   pst.setString(5,jpass.getText());
       pst.execute();
        JOptionPane.showMessageDialog(null, "Account Updated Successfully");
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
}
   }
   private void delete(){
    try{
        String sql = "SELECT * FROM users WHERE Account_id='"+acc_id.getText()+"'";
         pst = conn.prepareStatement(sql);
         rs=pst.executeQuery();
         if (rs.next()){
             String sql1 = "DELETE FROM users WHERE Account_id='"+acc_id.getText()+"'";
               pst = conn.prepareStatement(sql1);
             pst.execute();
             JOptionPane.showMessageDialog(null, "Account Deleted Permanently");
         }else{
             JOptionPane.showMessageDialog(null, "No Existing Data");
         }
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
}
}
}
